name: Run PyTest

on: workflow_dispatch

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.45.0-jammy
    steps:
        - uses: actions/checkout@v4
        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.12'
        - name: Install package and testing libraries
          run: |
            python -m pip install --upgrade pip 
            python -m pip install -e '.[tests]'
        # - name: Ensure browsers are installed
        #   run: |
        #     python -m pip install playwright
        #     python -m playwright install --with-deps
        - name: Test with webkit
          run: |
            pytest tests --numprocesses auto --reruns 5 --browser webkit
        - name: Test with firefox
          run: |
            pytest tests --numprocesses auto --reruns 5 --browser firefox
        - name: Test with chromium
          run: |
            pytest tests --numprocesses auto --reruns 5 --browser chromium
        # - uses: actions/upload-artifact@v4
        #   if: always()
        #   with:
        #     name: playwright-report
        #     path: playwright-report/
        #     retention-days: 30
